### ISSUE TITLE
Menu item handler index does not seem to be converted properly from WM_MENUCOMMAND

### ISSUE THREAD

**Issue by qoh** [luapower/winapi#2]
Whenever I try to use a window with a menubar, handlers never trigger. Further research shows that `Window:WM_MENUCOMMAND(menu, i)` -> `Menu:WM_MENUCOMMAND(i)` tries to run an appropriate handler by indexing on `i`, but that `i` is never converted from something like a value "0ULL" to an ordinary Lua number, causing the indexing to never succeed.

Adding `i = countfrom1(tonumber(i))` to `windowclass.lua:432` fixed it.

Additionally, several windows just crash `luajit.exe` when used (including but not limited to plain buttons - most, in fact). The demos do as well.

Worth noting that this is on WIndows 10, I suppose.

**Comment by capr** [comment]
Thanks for the bug report. Fixed[1].

I can't guarantee that you won't find any more of this type of bug on x64. Basically everything that is an int64 and ends up being used as a key in a table will hit this. This is a source of bugs in LuaJIT that I have to fix quite often. In winapi's case this hits all message decoders since MS decided wParam and lParam should be int64 on x64 (for no reason, since they can never hold 64bit values).

About the other crashes, I'll install a Windows 10 but please open specific bug reports so I can test on Win7 and WinXP first (these are the platforms that are most popular so I have to prioritize to them first). Thanks.

[1] https://github.com/luapower/winapi/commit/02231a0e291cf931d45ea74566892253498af089

**Comment by capr** [comment]
Hm, I just tested a bunch of demos (buttonclass, wglpanel_demo, comboboxclass, radiobuttonclass, etc.) and none of them crash on XP or Win7. So you'll have to be more specific.

**Comment by capr** [comment]
I'm closing this, please reopen if it you still have issues.
