### ISSUE TITLE
comctl32 v6 crash in x64

### ISSUE THREAD

**Issue by capr** [luapower/winapi#24]
All comctl32 controls (toolbars, buttons with autosize and margins, listview) crash on x64 with the comctl v6.0.0 manifest enabled. Without the manifest everything works fine (but then comctl 6 features are not available). The crash generally occurs on the first SendMessage() and it's very easy to reproduce (just run any demo of the above controls) though I'm out of ideas on what might cause it.

**Comment by nerditation** [comment]
I guess I have figured it out. let me try to briefly explain it:
in winapi/window.lua the function CallWindowProcW is incorrectly cdef-ed.
the type of the first arg lpPrevWndFunc should be WNDPROC but was declared as LONG.
thus the jit compiler truncated the address to 32 bits, resulting a memory access exception.

besides, the function SetWindowLong in winapi/window.lua had a similar bug. the last arg
should cast to LONG_PTR instead of LONG. however, this bug wouldn't cause crashes,
since the jit compiled address of MessageRouter.proc is within the lower 4G address space.

the fix should be trivial.

**Comment by capr** [comment]
Hi nerditation,

Thanks a lot for the fix (commit 7586fb64af3a59e6513183f2bb98a1e2065c6756).

These pesky LONG_PTRs have been bugging me before, I'm happy you squashed this one.

**Comment by Garrylua** [comment]
Great to see the fix, however I think there is still a bug.
If I add the following code to winapi_demo.lua at line 378:-

local str = lb.items:get(1)

it crashes. (works fine with luajit32)

I can fix it by modifying window.lua:718 from:-

return (C.SendMessageW(hwnd, flags(WM),

to:-

return tonumber(C.SendMessageW(hwnd, flags(WM),

but I'm not sure if that's the correct way to fix it.

**Comment by capr** [comment]
Thanks for reporting. Added #27 for that and I'll go through all SNDMSG calls and fix it.
